### ISSUE TITLE
Serving model with kserve

### ISSUE THREAD

**Issue by lanjewa** [tensorflow/gnn#141]
Hi Team,

I am looking for the serving gnn model with kserve. Also, it is possible to take list or numpy array as a input while preprocessing.
Actually, I want to pass list as input and while serving that list got converted into json which is the input for the request.post in kserving.

I am following below pattern.
![image](https://user-images.githubusercontent.com/115400319/194752914-92aa9218-9df9-4955-9e2c-71f5bf848600.png)

**Comment by arnoegw** [comment]
Hi @lanjewa, it seems no-one here had a good answer for your question. TF-GNN does not specifically provide support for kserve, but if kserve can handle TensorFlow SavedModels at all, those from TF-GNN should work as ususal:

Models built with TF-GNN can be exported as a TensorFlow SavedModel that accepts as input a batch of tf.Example protos with encoded GraphTensors. For an example, please see the section "Inference using Exported Model" near the bottom of our colab tutorial [Solving OGBN-MAG end-to-end with TF-GNN](https://colab.research.google.com/github/tensorflow/gnn/blob/master/examples/notebooks/ogbn_mag_e2e.ipynb#scrollTo=6B825Ydn6Vn5).

I hope that resolves the question. Please allow me to close this issue, as there is no actionable defect report or feature request here for the TF-GNN library. StackOverflow (with tags `[tensorflow-gnn]` and `[kubeflow-kserve]`) might reach more folks that can answer "how to" questions.
