### ISSUE TITLE
setup error

### ISSUE THREAD

**Issue by yifenzhong1920** [tensorflow/gnn#15]
bazel 1.0.0

unbutu: Ubuntu 5.4.0-6ubuntu1~16.04.10

tensorflow: 2.7

python: 3.9.6

When i execute the statement "python3 -m pip install ."  I got the error as follow:

Requirement already satisfied: absl-py in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-gnn==0.1.0) (1.0.0)
Requirement already satisfied: apache-beam[gcp]>=2.32 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-gnn==0.1.0) (2.34.0)
Requirement already satisfied: grpcio in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-gnn==0.1.0) (1.42.0)
Requirement already satisfied: matplotlib in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-gnn==0.1.0) (3.5.0)
Requirement already satisfied: mock in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-gnn==0.1.0) (4.0.3)
Requirement already satisfied: networkx in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-gnn==0.1.0) (2.6.3)
Requirement already satisfied: numpy in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-gnn==0.1.0) (1.20.3)
Requirement already satisfied: protobuf>=3.17 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-gnn==0.1.0) (3.19.1)
Requirement already satisfied: pyarrow in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-gnn==0.1.0) (5.0.0)
Requirement already satisfied: pygraphviz in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-gnn==0.1.0) (1.7)
Requirement already satisfied: scipy in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-gnn==0.1.0) (1.7.3)
Requirement already satisfied: six in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-gnn==0.1.0) (1.16.0)
Requirement already satisfied: tensorflow-cpu>=2.7.0 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-gnn==0.1.0) (2.7.0)
Requirement already satisfied: avro-python3!=1.9.2,<1.10.0,>=1.8.1 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.9.2.1)
Requirement already satisfied: crcmod<2.0,>=1.7 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.7)
Requirement already satisfied: dill<0.3.2,>=0.3.1.1 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (0.3.1.1)
Requirement already satisfied: fastavro<2,>=0.21.4 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.4.7)
Requirement already satisfied: future<1.0.0,>=0.18.2 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (0.18.2)
Requirement already satisfied: hdfs<3.0.0,>=2.1.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (2.6.0)
Requirement already satisfied: httplib2<0.20.0,>=0.8 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (0.19.1)
Requirement already satisfied: pymongo<4.0.0,>=3.8.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (3.12.1)
Requirement already satisfied: oauth2client<5,>=2.0.1 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (4.1.3)
Requirement already satisfied: pydot<2,>=1.2.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.4.2)
Requirement already satisfied: python-dateutil<3,>=2.8.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (2.8.2)
Requirement already satisfied: pytz>=2018.3 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (2021.3)
Requirement already satisfied: requests<3.0.0,>=2.24.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (2.26.0)
Requirement already satisfied: typing-extensions<4,>=3.7.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (3.10.0.2)
Requirement already satisfied: orjson<4.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (3.6.4)
Requirement already satisfied: cachetools<5,>=3.1.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (4.2.4)
Requirement already satisfied: google-apitools<0.5.32,>=0.5.31 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (0.5.31)
Requirement already satisfied: google-auth<3,>=1.18.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.35.0)
Requirement already satisfied: google-cloud-datastore<2,>=1.8.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.15.3)
Requirement already satisfied: google-cloud-pubsub<2,>=0.39.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.7.0)
Requirement already satisfied: google-cloud-bigquery<3,>=1.6.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (2.30.1)
Requirement already satisfied: google-cloud-bigquery-storage>=2.6.3 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (2.10.1)
Requirement already satisfied: google-cloud-core<2,>=0.28.1 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.7.2)
Requirement already satisfied: google-cloud-bigtable<2,>=0.31.1 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.7.0)
Requirement already satisfied: google-cloud-spanner<2,>=1.13.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.19.1)
Requirement already satisfied: grpcio-gcp<1,>=0.2.2 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (0.2.2)
Requirement already satisfied: google-cloud-dlp<2,>=0.12.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.0.0)
Requirement already satisfied: google-cloud-language<2,>=1.3.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.3.0)
Requirement already satisfied: google-cloud-videointelligence<2,>=1.8.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.16.1)
Requirement already satisfied: google-cloud-vision<2,>=0.38.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.0.0)
Requirement already satisfied: google-cloud-recommendations-ai<=0.2.0,>=0.1.0 in /usr/local/python3/lib/python3.9/site-packages (from apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (0.2.0)
Requirement already satisfied: fasteners>=0.14 in /usr/local/python3/lib/python3.9/site-packages (from google-apitools<0.5.32,>=0.5.31->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (0.16.3)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/python3/lib/python3.9/site-packages (from google-auth<3,>=1.18.0->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (0.2.8)
Requirement already satisfied: setuptools>=40.3.0 in /usr/local/python3/lib/python3.9/site-packages (from google-auth<3,>=1.18.0->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (56.0.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/python3/lib/python3.9/site-packages (from google-auth<3,>=1.18.0->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (4.8)
Requirement already satisfied: google-resumable-media<3.0dev,>=0.6.0 in /usr/local/python3/lib/python3.9/site-packages (from google-cloud-bigquery<3,>=1.6.0->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (2.1.0)
Requirement already satisfied: google-api-core[grpc]<3.0.0dev,>=1.29.0 in /usr/local/python3/lib/python3.9/site-packages (from google-cloud-bigquery<3,>=1.6.0->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.31.4)
Requirement already satisfied: proto-plus>=1.10.0 in /usr/local/python3/lib/python3.9/site-packages (from google-cloud-bigquery<3,>=1.6.0->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.19.8)
Requirement already satisfied: packaging>=14.3 in /usr/local/python3/lib/python3.9/site-packages (from google-cloud-bigquery<3,>=1.6.0->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (21.3)
Requirement already satisfied: googleapis-common-protos<2.0dev,>=1.6.0 in /usr/local/python3/lib/python3.9/site-packages (from google-api-core[grpc]<3.0.0dev,>=1.29.0->google-cloud-bigquery<3,>=1.6.0->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.53.0)
Requirement already satisfied: libcst>=0.2.5 in /usr/local/python3/lib/python3.9/site-packages (from google-cloud-bigquery-storage>=2.6.3->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (0.3.23)
Requirement already satisfied: grpc-google-iam-v1<0.13dev,>=0.12.3 in /usr/local/python3/lib/python3.9/site-packages (from google-cloud-bigtable<2,>=0.31.1->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (0.12.3)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/python3/lib/python3.9/site-packages (from google-resumable-media<3.0dev,>=0.6.0->google-cloud-bigquery<3,>=1.6.0->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.3.0)
Requirement already satisfied: docopt in /usr/local/python3/lib/python3.9/site-packages (from hdfs<3.0.0,>=2.1.0->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (0.6.2)
Requirement already satisfied: pyparsing<3,>=2.4.2 in /usr/local/python3/lib/python3.9/site-packages (from httplib2<0.20.0,>=0.8->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (2.4.7)
Requirement already satisfied: typing-inspect>=0.4.0 in /usr/local/python3/lib/python3.9/site-packages (from libcst>=0.2.5->google-cloud-bigquery-storage>=2.6.3->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (0.7.1)
Requirement already satisfied: pyyaml>=5.2 in /usr/local/python3/lib/python3.9/site-packages (from libcst>=0.2.5->google-cloud-bigquery-storage>=2.6.3->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (6.0)
Requirement already satisfied: pyasn1>=0.1.7 in /usr/local/python3/lib/python3.9/site-packages (from oauth2client<5,>=2.0.1->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (0.4.8)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/python3/lib/python3.9/site-packages (from requests<3.0.0,>=2.24.0->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/python3/lib/python3.9/site-packages (from requests<3.0.0,>=2.24.0->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (1.26.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/python3/lib/python3.9/site-packages (from requests<3.0.0,>=2.24.0->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/python3/lib/python3.9/site-packages (from requests<3.0.0,>=2.24.0->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (2.0.8)
Requirement already satisfied: h5py>=2.9.0 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (3.6.0)
Requirement already satisfied: keras<2.8,>=2.7.0rc0 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (2.7.0)
Requirement already satisfied: astunparse>=1.6.0 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (1.6.3)
Requirement already satisfied: termcolor>=1.1.0 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (1.1.0)
Requirement already satisfied: gast<0.5.0,>=0.2.1 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (0.4.0)
Requirement already satisfied: wrapt>=1.11.0 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (1.13.3)
Requirement already satisfied: wheel<1.0,>=0.32.0 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (0.37.0)
Requirement already satisfied: google-pasta>=0.1.1 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (0.2.0)
Requirement already satisfied: flatbuffers<3.0,>=1.12 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (2.0)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.21.0 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (0.22.0)
Requirement already satisfied: opt-einsum>=2.3.2 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (3.3.0)
Requirement already satisfied: tensorflow-estimator<2.8,~=2.7.0rc0 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (2.7.0)
Requirement already satisfied: tensorboard~=2.6 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (2.7.0)
Requirement already satisfied: keras-preprocessing>=1.1.1 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (1.1.2)
Requirement already satisfied: libclang>=9.0.1 in /usr/local/python3/lib/python3.9/site-packages (from tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (12.0.0)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/python3/lib/python3.9/site-packages (from tensorboard~=2.6->tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (3.3.6)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/python3/lib/python3.9/site-packages (from tensorboard~=2.6->tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (0.4.6)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/python3/lib/python3.9/site-packages (from tensorboard~=2.6->tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (0.6.1)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/python3/lib/python3.9/site-packages (from tensorboard~=2.6->tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (1.8.0)
Requirement already satisfied: werkzeug>=0.11.15 in /usr/local/python3/lib/python3.9/site-packages (from tensorboard~=2.6->tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (2.0.2)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/python3/lib/python3.9/site-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (1.3.0)
Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/python3/lib/python3.9/site-packages (from markdown>=2.6.8->tensorboard~=2.6->tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (4.8.2)
Requirement already satisfied: zipp>=0.5 in /usr/local/python3/lib/python3.9/site-packages (from importlib-metadata>=4.4->markdown>=2.6.8->tensorboard~=2.6->tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (3.6.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/python3/lib/python3.9/site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard~=2.6->tensorflow-cpu>=2.7.0->tensorflow-gnn==0.1.0) (3.1.1)
Requirement already satisfied: mypy-extensions>=0.3.0 in /usr/local/python3/lib/python3.9/site-packages (from typing-inspect>=0.4.0->libcst>=0.2.5->google-cloud-bigquery-storage>=2.6.3->apache-beam[gcp]>=2.32->tensorflow-gnn==0.1.0) (0.4.3)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/python3/lib/python3.9/site-packages (from matplotlib->tensorflow-gnn==0.1.0) (4.28.2)
Requirement already satisfied: cycler>=0.10 in /usr/local/python3/lib/python3.9/site-packages (from matplotlib->tensorflow-gnn==0.1.0) (0.11.0)
Requirement already satisfied: pillow>=6.2.0 in /usr/local/python3/lib/python3.9/site-packages (from matplotlib->tensorflow-gnn==0.1.0) (8.4.0)
Requirement already satisfied: setuptools-scm>=4 in /usr/local/python3/lib/python3.9/site-packages (from matplotlib->tensorflow-gnn==0.1.0) (6.3.2)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/python3/lib/python3.9/site-packages (from matplotlib->tensorflow-gnn==0.1.0) (1.3.2)
Requirement already satisfied: tomli>=1.0.0 in /usr/local/python3/lib/python3.9/site-packages (from setuptools-scm>=4->matplotlib->tensorflow-gnn==0.1.0) (1.2.2)
Building wheels for collected packages: tensorflow-gnn
  Building wheel for tensorflow-gnn (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-nf5s7_74/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-nf5s7_74/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-8jo1b0me
       cwd: /tmp/pip-req-build-nf5s7_74/
  Complete output (35 lines):
  running bdist_wheel
  running build
  running bazel_build
  Starting local Bazel server and connecting to it...
  ERROR: Unrecognized option: --experimental_repo_remote_exec
  INFO: Writing tracer profile to '/root/.cache/bazel/_bazel_root/958b14b9bd3acfff4092d0b52e211899/command.profile.gz'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-nf5s7_74/setup.py", line 152, in <module>
      setup(
    File "/usr/local/python3/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/python3/lib/python3.9/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/python3/lib/python3.9/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/python3/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/python3/lib/python3.9/site-packages/wheel/bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "/usr/local/python3/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/python3/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/python3/lib/python3.9/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/python3/lib/python3.9/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/python3/lib/python3.9/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-nf5s7_74/setup.py", line 86, in run
      subprocess.check_call(
    File "/usr/local/python3/lib/python3.9/subprocess.py", line 373, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/bazel', 'run', '-c', 'opt', '--experimental_repo_remote_exec', '//package:move_generated_files']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for tensorflow-gnn
  Running setup.py clean for tensorflow-gnn
Failed to build tensorflow-gnn
Installing collected packages: tensorflow-gnn
    Running setup.py install for tensorflow-gnn ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-nf5s7_74/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-nf5s7_74/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rsfpi3kt/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/python3/include/python3.9/tensorflow-gnn
         cwd: /tmp/pip-req-build-nf5s7_74/
    Complete output (36 lines):
    running install
    running build
    running bazel_build
    ERROR: Unrecognized option: --experimental_repo_remote_exec
    INFO: Writing tracer profile to '/root/.cache/bazel/_bazel_root/958b14b9bd3acfff4092d0b52e211899/command.profile.gz'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-nf5s7_74/setup.py", line 152, in <module>
        setup(
      File "/usr/local/python3/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/python3/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/python3/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/python3/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/python3/lib/python3.9/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/python3/lib/python3.9/distutils/command/install.py", line 546, in run
        self.run_command('build')
      File "/usr/local/python3/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/python3/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/local/python3/lib/python3.9/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/local/python3/lib/python3.9/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/python3/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-nf5s7_74/setup.py", line 86, in run
        subprocess.check_call(
      File "/usr/local/python3/lib/python3.9/subprocess.py", line 373, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/bin/bazel', 'run', '-c', 'opt', '--experimental_repo_remote_exec', '//package:move_generated_files']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-nf5s7_74/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-nf5s7_74/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-rsfpi3kt/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/python3/include/python3.9/tensorflow-gnn Check the logs for full command output.

**Comment by rish-16** [comment]
Hey, @dmadisetti is absolutely right! It's a bazel build issue but it has a hack-y fix:

Clone the repo locally, go to the `package/` directory, and edit your `BUILD` file. The original content is,

```
licenses(["notice"])  # Apache 2.0

config_setting(
    name = "windows",
    constraint_values = [
        "@bazel_tools//platforms:windows",
    ],
)

sh_binary(
    name = "move_generated_files",
    srcs = ["move_generated_files.sh"],
    data = [
        "//tensorflow_gnn/proto:examples_pb2.py",
        "//tensorflow_gnn/proto:graph_schema_pb2.py",
        "//tensorflow_gnn/sampler:subgraph_pb2.py",
        "//tensorflow_gnn/sampler:sampling_spec_pb2.py",
        "//tensorflow_gnn/tools:sampled_stats_pb2.py",
    ],
)
```

## The Fix
There's the line `"//tensorflow_gnn/sampler:subgraph_pb2.py",` that has to be removed. This is because this file was removed in a more recent commit but the bazel build wasn't updated to reflect those changes. 

Once you remove this line (while keeping the others), go ahead and `python3 -m pip install .` again. Your installation should run smoothly.

---

Check out #7 for more. Hope this helps!

**Comment by dmadisetti** [comment]
Also see #16
Number #13 also provides a fix

**Comment by sibonli** [comment]
This should now be fixed with the latest update!
