### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by jackd** [tensorflow/gnn#19]
Is there a prefered way of citing this repository in academic articles? Could a .bib entry be provided either here or in the READMEmd?

**Comment by phanein** [comment]
Thanks, this was added a while ago, just following up to close the issue.

@article{tfgnn,
  author  = {Oleksandr Ferludin and Arno Eigenwillig and Martin Blais and
             Dustin Zelle and Jan Pfeifer and Alvaro Sanchez{-}Gonzalez and
             Sibon Li and Sami Abu{-}El{-}Haija and Peter Battaglia and
             Neslihan Bulut and Jonathan Halcrow and
             Filipe Miguel Gon{\c{c}}alves de Almeida and Silvio Lattanzi and
             Andr{\'{e}} Linhares and Brandon Mayer and Vahab Mirrokni and
             John Palowitch and Mihir Paradkar and Jennifer She and
             Anton Tsitsulin and Kevin Villela and Lisa Wang and David Wong and
             Bryan Perozzi},
  title   = {{TF-GNN:} Graph Neural Networks in TensorFlow},
  journal = {CoRR},
  volume  = {abs/2207.03522},
  year    = {2022},
  url     = {http://arxiv.org/abs/2207.03522},
}
