### ISSUE TITLE
Can you provide this package via PyPI?

### ISSUE THREAD

**Issue by jeongukjae** [tensorflow/gnn#2]
Even though it is in early release, but if we can install this package using pip like `pip install tensorflow-gnn`, it will be great!

**Comment by mihirparadkar** [comment]
Hi, we're currently working on releasing a binary distribution for Linux and a source distribution on PyPI. Stay tuned!

**Comment by jeongukjae** [comment]
Hi, I could check this package has been uploaded PyPI at this link. 

https://pypi.org/project/tensorflow-gnn/
