### ISSUE TITLE
The tutorial code in document data_prep.md doesn't work

### ISSUE THREAD

**Issue by Hanc1999** [tensorflow/gnn#229]
In the doc ['data_prep.md' ](https://github.com/tensorflow/gnn/blob/d9af52ff16fdb107a807a18f35b8dc05efa0ffa2/tensorflow_gnn/docs/guide/data_prep.md), it seems like the code piece <code>graph = tfgnn.random_graph_tensor_from_schema(schema)</code> in the first code block raises an error that there's no such callable function (with tfgnn version=0.3.0).

details:
<code>
AttributeError: module 'tensorflow_gnn' has no attribute 'random_graph_tensor_from_schema'
</code>

**Comment by arnoegw** [comment]
Thank you, @Hanc1999 , for your report. Indeed, this symbol is missing. I'll look into it.

**Comment by arnoegw** [comment]
@aferludin has fixed the doc with commit https://github.com/tensorflow/gnn/commit/55520d877cbb08f27d0d9478330540dd18c386d8: we recommend that users apply `tfgnn.create_graph_spec_from_schema_pb()` followed by `tfgnn.random_graph_tensor()`.

Thank you again for the report, and for your patience.
