### ISSUE TITLE
To use local file

### ISSUE THREAD

**Issue by SidneyLann** [tensorflow/gnn#23]
How to use local file tensorflow-2.7.0.tar.gz and DO NOT download from below bazel settings:

"""Dependency on TensorFlow for build."""

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

def tf_setup():
    """Define tensorflow>=2.7.0 dependency for Bazel build."""
    http_archive(
        name = "org_tensorflow",
        sha256 = "41b32eeaddcbc02b0583660bcf508469550e4cd0f86b22d2abe72dfebeacde0f",
        urls = [
            "https://github.com/tensorflow/tensorflow/archive/refs/tags/v2.7.0.tar.gz",
        ],
        strip_prefix = "tensorflow-2.7.0",
    )

**Comment by dmadisetti** [comment]
You can use bazel's `local_repository` rule: https://docs.bazel.build/versions/main/be/workspace.html#local_repository

Or you can find and pin a particular commit

**Comment by SidneyLann** [comment]
It work. Thanks. But too many files need to download used by tf when compile tf-gnn, so it is hard to compile tf-gnn when bandwidth is a problem. Why tf-gnn still try to compile tf despite the tf had been installed!

**Comment by dmadisetti** [comment]
Yes, tensorflow is a pain to build from scratch. Bazel guarantees hermeticity and reproducibility which means it has to do everything itself.

But it's also pretty good at caching, meaning after your first build it should be much quicker

**Comment by SidneyLann** [comment]
Why tf-gnn can't use the installed tf and compile new one? And why install the tf then?

**Comment by dmadisetti** [comment]
The only bazel dependencies I can find are just the protos https://github.com/tensorflow/gnn/blob/f63478419152cc2f22886173b45302323f4bfc56/tensorflow_gnn/proto/BUILD#L15 so I'm not sure the full of tensorflow is being installed.

The tensorflow that is used in the python library is actually installed here https://github.com/tensorflow/gnn/blob/f63478419152cc2f22886173b45302323f4bfc56/setup.py#L193

**Comment by SidneyLann** [comment]
workspace(name = "tensorflow_gnn")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# Define the TensorFlow archive.
load("//package:tfdep.bzl", "tf_setup")
tf_setup()

# Initialize the TensorFlow repository and all dependencies.
# See @org_tensorflow//WORKSPACE for details.
load("@org_tensorflow//tensorflow:workspace3.bzl", "tf_workspace3")
tf_workspace3()
load("@org_tensorflow//tensorflow:workspace2.bzl", "tf_workspace2")
tf_workspace2()
load("@org_tensorflow//tensorflow:workspace1.bzl", "tf_workspace1")
tf_workspace1()
load("@org_tensorflow//tensorflow:workspace0.bzl", "tf_workspace0")
tf_workspace0()

# This seems required to avoid a proxy setup.
# TODO(blais): Find a way to get rid of this.
http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "1698624e878b0607052ae6131aa216d45ebb63871ec497f26c67455b34119c80",
    strip_prefix = "rules_docker-0.15.0",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/v0.15.0.tar.gz"],
)





Above is the content in tf-gnn/WORKSPACE file, so I think whole tf is compiled.

**Comment by sibonli** [comment]
Hi Sidney, 

As Dylan mentions above, we do have a dependency on protos that requires us to build the entire repo. Apologize for the inconvenience.

**Comment by SidneyLann** [comment]
OK. Thanks.

**Comment by SidneyLann** [comment]
Successfully built tensorflow-gnn
Installing collected packages: tensorflow-gnn
Successfully installed tensorflow-gnn-0.1.0
