### ISSUE TITLE
How to get node_set_name dynamic?

### ISSUE THREAD

**Issue by SidneyLann** [tensorflow/gnn#230]
tfgnn.gather_first_node(
            graph_tensor, node_set_name=node_set_name, feature_name='label'
        )

The node_set_name is dynamic for multiple node sets in a graph tensor, how to get the node set name dynamic?

**Comment by SidneyLann** [comment]
tf.config.run_functions_eagerly(True), if use this line, exception occors:
Exception encountered when calling layer "gat_v2_convolution" (type GATv2Convolution).

indices[1787] = 2087 is not in [0, 2048) [Op:GatherV2]

Call arguments received:
  • graph=<tensorflow_gnn.graph.graph_tensor.GraphTensor object at 0x7f65d2c23e80>
  • edge_set_name='Biz-Biz'
  • node_set_name=None
  • receiver_tag=None
  • training=True

And if not to use above line, then can't get the node_set_name in Tensor("data:0", shape=(32,), dtype=string)

**Comment by phanein** [comment]
Hi @SidneyLann, 

I don't totally understand the use case here yet, but I can offer the following advice -- 

1. Usually we define the network's architecture statically over a graph schema (not dynamically).  So if you wanted to apply GATv2 to two node sets ("A", "B"), we'd instantiate two convolutions (one for node set "A", and one for set "B").

2. If you wanted to apply a function independent of node set id, you might look at [this example](https://github.com/tensorflow/gnn/blob/main/tensorflow_gnn/runner/examples/ogbn/mag/train.py#L227) which applies [VanillaMPNNGraphUpdate](https://github.com/tensorflow/gnn/blob/main/tensorflow_gnn/models/vanilla_mpnn/layers.py#L22) to everything.

If you have a minimum working example that illustrates what you're trying to achieve, we can probably offer more specific advice.
