### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow_gnn.proto.graph_schema_pb2'

### ISSUE THREAD

**Issue by SidneyLann** [tensorflow/gnn#24]
ModuleNotFoundError: No module named 'tensorflow_gnn.proto.graph_schema_pb2' when run gat_v2_test.py. Where is the graph_schema_pb2 file? it is py or proto file?

**Comment by SidneyLann** [comment]
Same error when run this example https://github.com/yarri-oss/gnn/blob/main/examples/citeseer/graph_tensor_example.py

**Comment by SidneyLann** [comment]
@joshcarty Do you have this issue when you run gat_v2_test.py? Thank you.

**Comment by joshcarty** [comment]
Answered [here](https://github.com/tensorflow/gnn/issues/5#issuecomment-1034751805).

I'd also be wary of using the above fork - it's from an older version of the package and quite a few changes have been made since, including the removal of those examples.

**Comment by SidneyLann** [comment]
Had run the command before.



![image](https://user-images.githubusercontent.com/5990314/153432789-eb5293d0-cf29-4d24-8ab4-b1a73506032b.png)



should have no error in the highlight box in pycharm if everything installed correctly?

**Comment by SidneyLann** [comment]
Thank you. The reason is my tf can't install successfully.

1. My cpu does not support avx, so I comment #'tensorflow>=2.7.0', in setup.py and build tf by myself.
2. Use pip to install my tf but got ERROR: tensorflow-2.7.0-cp39-cp39-linux_x86_64.whl is not a supported wheel on this platform.
3. Use sudo pip to install my tf successfully.
4. Why tf build in my OS can't install to my Os by general user but can install it successfully by super user?

**Comment by SidneyLann** [comment]
It seems general user use /home/sidney/.local/bin/pip3.8 and super user use /usr/local/bin/pip3.9 cause the problem.

**Comment by SidneyLann** [comment]
ssh://sidney@192.168.56.102:22/usr/bin/python -u /home/sidney/py_proj/tf-gnn/tensorflow_gnn/graph/keras/layers/gat_v2_test.py
free(): invalid pointer

Process finished with exit code 134



this error occur after all installed correctly, what's the problem?

**Comment by SidneyLann** [comment]
![image](https://user-images.githubusercontent.com/5990314/153593447-cf64af62-3229-4a9d-a465-98f136eda3da.png)


So the tf is not installed correctly? How to solve this problem then?

**Comment by SidneyLann** [comment]
Run gat_v2_test.py successfully now. But need copy the generated file graph_schema_pb2.py to the proto folder, is it normal?

**Comment by fidel-schaposnik** [comment]
To get around this error, clone the main TensorFlow repository, then manually compile the protocol buffer files in the proto directory. Assuming you are working from your home directory:
```
pip install grpcio grpcio-tools
git clone https://github.com/tensorflow/tensorflow.git
python -m grpc_tools.protoc -I ~/tensorflow_gnn/tensorflow_gnn/proto/ -I ~/tensorflow --python_out=~/tensorflow_gnn/tensorflow_gnn/proto/ graph_schema.proto
python -m grpc_tools.protoc -I ~/tensorflow_gnn/tensorflow_gnn/proto/ -I ~/tensorflow --python_out=~/tensorflow_gnn/tensorflow_gnn/proto/ examples.proto
```

**Comment by SidneyLann** [comment]
Thanks. This just generate graph_schema_pb2.py from graph_schema.proto in proto folder, right? it is generated in another place when install tensorflow_gnn, and just need to copy it to proto folder.
