### ISSUE TITLE
Accessing GATv2Convolution

### ISSUE THREAD

**Issue by fidel-schaposnik** [tensorflow/gnn#25]
I am somewhat confused by the way TensorFlow GNN exposes GATv2 and related layers. I see that both `tfgnn.keras.layers.GATv2` and `tfgnn.keras.layers.gat.gatv2.GATv2` are available, but what is the difference between them? `tfgnn.keras.layers.gat.gatv2.GATv2AttentionPool` is also available, but I can't seem to access `GATv2GraphUpdate`, `GATv2EdgePool` or `GATv2Convolution` from https://github.com/tensorflow/gnn/blob/main/tensorflow_gnn/graph/keras/layers/gat_v2.py , the latter of which also supports edge features (as opposed to the GATv2 that is exposed).

Also, I see in https://github.com/tensorflow/gnn/blob/main/tensorflow_gnn/graph/keras/keras_e2e_test.py there is a test `self.assertIsSubclass(tfgnn.keras.layers.GATv2Convolution, Layer)`, but this of course fails.

**Comment by arnoegw** [comment]
For the record: This was cleaned up for tensorflow-gnn 0.2.0, please see

https://github.com/tensorflow/gnn/blob/r0.2/tensorflow_gnn/docs/api_docs/python/models/gat_v2.md

https://github.com/tensorflow/gnn/tree/r0.2/tensorflow_gnn/models/gat_v2
