### ISSUE TITLE
setup.py' nor 'pyproject.toml' found at Installation step 5

### ISSUE THREAD

**Issue by cloudlakecho** [tensorflow/gnn#27]
Thanks for putting the detailed installation step. 

I follow the installation step at the read me web page. I maneuver to reach at the last step, which is 5:

5. Install tensorflow_gnn

    `$> cd tensorflow_gnn && python3 -m pip install .`

I face the error message:

&nbsp;&nbsp;&nbsp;&nbsp;ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.  

The tensorflow_gnn folder looks like not haing the `setup.py` file. Should I use the `setpu.py` file at the gnn folder, which is the parent folder of the tensorflow_gnn?

Runtime environment:
&nbsp;&nbsp;&nbsp;&nbsp;OS: Windows 10
&nbsp;&nbsp;&nbsp;&nbsp;Virtual environment: Anaconda
&nbsp;&nbsp;&nbsp;&nbsp;Bazel: 5.0
&nbsp;&nbsp;&nbsp;&nbsp;Tensowflow: 2.7
&nbsp;&nbsp;&nbsp;&nbsp;Python: 3.8.12

**Comment by SidneyLann** [comment]
python_requires='>=3.9,<4',

**Comment by cloudlakecho** [comment]
@SidneyLann thanks for indication of Python version. I actually tried with Python 3.9 but it didn't result correctly. 
I ran the command (`pip install .`) at the "gnn" folder (not "gnn/tensorflow_gnn"), and it installed related dependent tools. 

For this reason, I want to suggest `python3 -m pip install .` as a solution for my own problem.
