### ISSUE TITLE
Understanding of "sizes" for edges in the case of more components

### ISSUE THREAD

**Issue by alem88** [tensorflow/gnn#272]
Here, at this link https://github.com/tensorflow/gnn/blob/main/tensorflow_gnn/graph/graph_tensor.py#L749  I tried to understand that example

```python
  # A scalar graph tensor with edges between authors, papers and their venues
  # (journals or conferences). Each venue belongs to one graph component. The
  # 1st venue (1980519) has 2 authors and 3 papers.
  # The 2nd venue (9756463) has 2 authors and 1 paper.
  # The paper 0 is written by authors 0 and 2; paper 1 - by authors 0 and 1;
  # paper 2 - by author 2; paper 3 - by author 3.
  venues = tfgnn.GraphTensor.from_pieces(
      context=tfgnn.Context.from_fields(
          features={'venue': [1980519, 9756463]}),
      node_sets={
          'author': tfgnn.NodeSet.from_fields(sizes=[2, 2], features={}),
          'paper': tfgnn.NodeSet.from_fields(
              sizes=[3, 1], features={'year': [2018, 2017, 2017, 2022]})},
      edge_sets={
          'is_writen': tfgnn.EdgeSet.from_fields(
              sizes=[4, 2],
              features={},
              adjacency=tfgnn.Adjacency.from_indices(
                  source=('paper', [0, 1, 1, 0, 2, 3]),
                  target=('author', [0, 0, 1, 2, 3, 3])))})
  ```

I just don't understand this [4,2] part and the relation with source and target parts...

Is it like 4 means 4 papers and 2 means 2 authors, or this 2 comes from number of components (journals or conferences)?

I definitely see there are 6 edges present (4+2), but how to understand this 4 and 2 in this context?

From the part "paper 2 - by author 2; paper 3 - by author 3", we can see that there is one small mistake in this example, and that is in target part, it should be [0, 0, 1, 2, 2, 3] instead of [0, 0, 1, 2, 3, 3] (or maybe it is the case that paper 2 - by author 3)?

Now, how can we understand from these which paper belongs to 1th and which one to 2nd venue?

**Comment by arnoegw** [comment]
Hi @alem88

> I definitely see there are 6 edges present (4+2), but how to understand this 4 and 2 in this context?

That example graph contains two **components**. All `size` fields report the sizes per component, so in this particular edge set, there are 4 edges in the first component and 2 edges in the second component.

The TF-GNN docs explain the notion of component [here](https://github.com/tensorflow/gnn/blob/main/tensorflow_gnn/docs/guide/graph_tensor.md#components-and-context). They allow `GraphTensor` to store a whole batch of input graphs as one graph with contiguously indexed nodes and edges, but without losing track of the boundaries of the original inputs. For additional motivation, please see [here](https://github.com/tensorflow/gnn/blob/main/tensorflow_gnn/docs/guide/input_pipeline.md#merging-a-batch-of-inputs-into-components-of-one-graph) how they fit into a typical input pipeline to a GNN model.

Did that answer your question? Please reopen this issue if there is a problem with the referenced documentation.
