### ISSUE TITLE
Support for bidirectional edges?

### ISSUE THREAD

**Issue by DiTo97** [tensorflow/gnn#282]
Hi,

I was wondering if there was a built-in way to flag an edge as bidirectional, rather than having to duplicate connections in the base data source (e.g., Pandas dataframe) between nodes

**Comment by phanein** [comment]
Hi @DiTo97 

I don't think we have a utility function for this right now -- its usually not a problem w.r.t. message passing though, since one can pass messages over either end of a directed edge, (this is configured e.g. by `receiver_tag=tfgnn.SOURCE` in a `NodeSetUpdate`).

**Comment by arnoegw** [comment]
Hi @DiTo97 

We are using GitHub issues to track defect reports and actionable feature requests for the TF-GNN library. I am sorry to say this, but we are not able to provide 1-1 coding advice beyond the tutorials that we have prepared for the library. [This one here](https://colab.research.google.com/github/tensorflow/gnn/blob/master/examples/notebooks/ogbn_mag_indepth.ipynb#scrollTo=b7fhATRUexKh) shows a big invocation of `tfgnn.keras.layers.GraphUpdate` in which it is easy to spot the use of receiver tags, which @phanein mentioned. (Recall that a Conv must appear with its receiver node set, so take care to move it when flipping the tag.)

For further "how to" questions on coding, please allow me to suggest StackOverflow, which now has a [[tensorflow-gnn]](https://stackoverflow.com/questions/tagged/tensorflow-gnn) tag.
