### ISSUE TITLE
Imports

### ISSUE THREAD

**Issue by itisthoughttobemaeri** [tensorflow/gnn#314]
Hi, I am following your tutorials on Colab to start diving into GNN, but the code doesn't allow me to import `tensorflow_gnn.in_memory` and I get the error `ModuleNotFoundError: No module named 'tensorflow_gnn.in_memory'`.

**Comment by phanein** [comment]
HI @itisthoughttobemaeri  - thanks for your interest.  

I'm not sure what colab (or tf-gnn version) this is from, but it seems like a versioning issue -- the dependency should currently  be at `tensorflow_gnn.experimental.in_memory`.

**Comment by arnoegw** [comment]
I tried just now on https://colab.research.google.com, and the following works as expected

```
!pip install -q tensorflow-gnn   # Gives me 0.5.0
import tensorflow as tf
import tensorflow_gnn as tfgnn
from tensorflow_gnn.experimental.in_memory import models
from tensorflow_gnn.experimental.in_memory import reader_utils
```

@itisthoughttobemaeri , does the problem still exist? If so, please provide specific repro instructions (such as a brief Colab notebook shared on Google Drive).

**Comment by arnoegw** [comment]
I suppose the problem has gone away. Please reopen with specific repro instructions if it still exists. Much appreciated!

**Comment by iiternalfire** [comment]
I think the tutorial colab doesn't seem to work now due to some dependency or compatibility issue:
![image](https://github.com/tensorflow/gnn/assets/8063769/f3298abb-4529-495a-97ed-6abb4acb2424)

When I ran the above minimal example from @arnoegw in Google colab, I got the following pip issue: 
![image](https://github.com/tensorflow/gnn/assets/8063769/a5f79d93-0078-4231-b4cd-f543a6011714)

Any fix for this issue?

**Comment by arnoegw** [comment]
Hi @iiternalfire!

For release 1.0, the `experimental.in_memory` code has been replaced by a production-ready implementation of in-memory sampling; please see the new [In-memory Sampler](https://github.com/tensorflow/gnn/blob/main/tensorflow_gnn/docs/guide/inmemory_sampler.md) guide. The [OGBN-MAG End-to-End](https://colab.research.google.com/github/tensorflow/gnn/blob/master/examples/notebooks/ogbn_mag_e2e.ipynb) colab has been updated accordingly and demonstrates its intended usage.

The notebooks under `examples/tutorials/<venue>/...` reflect the original presentations as given at the respective venue; you'll have to `pip install --pre tensorflow_gnn~=0.6.0` to run that code unchanged.

Hope that helps...
