### ISSUE TITLE
onnx/tensorrt/triton support

### ISSUE THREAD

**Issue by philip-fu** [tensorflow/gnn#33]
Does it support exporting model to be used with triton server?

**Comment by arnoegw** [comment]
Thanks for your interest in TF-GNN! A TF-GNN model can be exported like any other TensorFlow or Keras model without custom ops. The standard way is a TF2 SavedModel. Whatever does or does not apply for that should just carry over.

**Comment by frytoli** [comment]
Hi there! I'm hoping to export a trained TFGNN model to ONNX as well. However, the layer `tfgnn.keras.layers.ParseExample` which is included in the documentation for both the [input pipeline](https://github.com/tensorflow/gnn/blob/main/tensorflow_gnn/docs/guide/input_pipeline.md#file-input-and-parsing) and [model saving](https://github.com/tensorflow/gnn/blob/main/tensorflow_gnn/docs/guide/model_saving.md#basics) is not supported by ONNX ([tensorflow-onnx/issues/825](https://github.com/onnx/tensorflow-onnx/issues/825)). Therefore, I need to export an inference model that does not require or include a Tensorflow protobuf-parsing layer (I guess I could attempt to write my own parsing layer and register it with ONNX, but that seems a bit extreme). The previously linked issue seems to recommend "[loading] the saved model and [adding] a new interface to the saved-model that uses placeholders".

Does the TFGNN team have input on how best to do this? Is there a way to pass graph (i.e. node, edge, and adjacency) features as input to an exported model that will then create the input graph with something like `tfgnn.GraphTensor.from_pieces`? Might a [custom serving function](https://github.com/tensorflow/docs/blob/master/site/en/r1/guide/saved_model.md#prepare-serving-inputs) be required?

Any help would be greatly appreciated -- thank you!

**Comment by arnoegw** [comment]
Hi @frytoli , I think your plan is good: pass free-standing Tensors for adjacency and features into the model, then use `tfgnn.GraphTensor.from_pieces`.

This is also what we do for using GraphTensor inside (but not at the interface of) models deployed to TFLite. You can see an example of this technique in the unit test [VanillaMPNNTFLiteTest.testBasic](https://github.com/tensorflow/gnn/blob/r1.0/tensorflow_gnn/models/vanilla_mpnn/layers_test.py#L80). It wraps the call to `tfgnn.GraphTensor.from_pieces` in an ad-hoc Keras layer _MakeGraphTensor.

To export a SavedModel that hides the use of TF-GNN inside and looks like any other TensorFlow SavedModel, please follow the [Model Saving Guide](https://github.com/tensorflow/gnn/blob/r1.0/tensorflow_gnn/docs/guide/model_saving.md) (new as of TF-GNN 1.0). The TL;DR is: with TF2.13+, use Keras `Model.export()`.

**Comment by frytoli** [comment]
That's exactly what I needed! Thanks @arnoegw.
