### ISSUE TITLE
Order of edges resp. nodes in a GraphTensor when reading out a prediction head

### ISSUE THREAD

**Issue by kk-55** [tensorflow/gnn#348]
_I know that this is no issue, but I don't know any forum or channel to ask questions regarding TF-GNN._

### Let's assume the following simple scenario:
A graph with n=4 nodes and m=4 edges each having a single feature array.
The adjacency for this edge set might look like as follows

- source = [0, 0, 0, 2]
- target = [1, 2, 3, 1]

I.e., node with index 0 is connected to nodes with indicies 1, 2, 3 and node with index 2 is also connected to node 1.

The GraphTensor stores the node set features in a tensor with shape [4, ...] and the edge set features in a tensor with shape [4, ...].
AFAIK, nodes are indexed 0, 1, ..., 3 and feature array at tensor index 0 in the outer dimension belongs to node 0, feature array at tensor index 1 in the outer dimension belongs to node 1 and so on. The same should hold for the edge set and its features.

For me, this means that the order of nodes and edges is derived from their feature tensors. More precisely, feature value at index 0 then belongs to node/edge 0 and so on.
Furthermore, edge 0 is the one which connects node 0 to node 1, edge 1 connects node 0 to node 2 and so on.

**Provided it is correct up to here, after rounds of updates and manipulations will the order of nodes and edges still be the same as for the input GraphTensor? Especially in the case, when I want to read out states for a final prediction head to classify nodes resp. edges?
Think of a reinforcement learning use case, where actions are associated with edges and a prediction head classifies each edge with a score/probability. Thus, it is essential to know the order of edges in such a final output tensor to select the correct edge resp. action.**

**Briefly asked, will the order of nodes and edges be preserved in a GraphTensor, from input until readout of a final prediction head?**

**Comment by mihirparadkar** [comment]
Hi!

The preservation of node/edge order depends on the type of model you're using. Most of the models we implement (vanilla MPNN, HGT, multi-head attention, etc.) don't change the order, but we may implement architectures in the future that do.

As for the correct forum/channel for TF-GNN questions, please consider posting to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow-gnn)

**Comment by arnoegw** [comment]
Please allow me to close this. I think @kk-55's question has been answered.
