### ISSUE TITLE
RaggedTensor in GCN

### ISSUE THREAD

**Issue by JachyMeow** [tensorflow/gnn#355]
When I use `tensorflow_gnn.models.gcn.gcn_conv.GCNConv`, I got an error: 
`ValueError: The last dimension of the inputs to a Dense layer should be defined. Found None. Full input shape received: (90, None)`. 

After checking `GCNConv`, I found out that one of the `features` of `node_sets` is a `tf.RaggedTensor`, and its shape is exactly `(90, None)`.

Then, how can I run `GCNConv` with `tf.RaggedTensor`?

**Comment by Neslihans** [comment]
GCNConv is working on dense tensors, but I wonder if you need a RaggedTensor for some reason. Can you please add more details for your application?
Can you convert this to a dense tensor first during initial feature mapping stage, before feeding the graph into GCNConv?

**Comment by JachyMeow** [comment]
I see... 
But it's hard to convert the RaggedTensor to a dense tensor. I may delete the feature. 
Thanks!

**Comment by Neslihans** [comment]
Based on your input data type you can try Keras's preprocessing layers here: https://keras.io/guides/preprocessing_layers/, and let's say if you have embeddings learnt over the features then you can apply an aggregate(maybe an average) of the ragged dimensions. This will give you dense representations.

Also ragged tensors have [to_tensor()](https://www.tensorflow.org/api_docs/python/tf/RaggedTensor?version=nightly#to_tensor) function that will convert to dense tensor.
