### ISSUE TITLE
which version of python is needed?

### ISSUE THREAD

**Issue by paravatha** [tensorflow/gnn#4]
Hi, do we need python 3.9 for this to work?
if we do, can you please update the README.md?

**Comment by sibonli** [comment]
Hi Prasad, 

As specified, in setup.py, we require Python 3.9 to run as some of our functionality requires some features from 3.9.

**Comment by cloudlakecho** [comment]
@paravatha Have you successfully installed the GNN? If yes, did you had an error at [the step 5](https://github.com/tensorflow/gnn)?

**Comment by joshcarty** [comment]
I've been running into some challenges with this requirement.

For example:
* Beam officially only supports up to [Python 3.8](https://beam.apache.org/get-started/quickstart-py/). Running jobs with the direct runner works but you can't run jobs on DataFlow as it doesn't support [Python 3.9](https://cloud.google.com/dataflow/docs/support/beam-runtime-support). This is a challenge for scaling the sampling described in the [Data Prep guide](https://github.com/tensorflow/gnn/blob/main/tensorflow_gnn/docs/guide/data_prep.md).
* TFX only supports [Python 3.8](https://github.com/tensorflow/tfx/blob/master/setup.py#L356). This makes it challenging to build a pipeline with the package using the standard TensorFlow ecosystem.
* TensorFlow Transform doesn't have a requirement preventing you from using Python 3.9. However, I've been unable to successfully install it (can share more details but probably less relevant here). This makes it challenging to build and scale a reliable feature engineering pipeline.

@sibonli, @arnoegw, @janpfeifer, I was wondering which features of Python 3.9 you were relying on? I think supporting 3.8 instead could really help the package integrate better with the broader TensorFlow ecosystem. How feasible it would be to relax that requirement on 3.9?

Keen to support where I can. Thanks!

**Comment by arnoegw** [comment]
tensorflow-gnn 0.2.0 now supports Python versions >=3.7, <4, that is, all currently active Python releases per https://www.python.org/downloads/
