### ISSUE TITLE
No package 'arrow-python' found

### ISSUE THREAD

**Issue by PeterDeSOM** [tensorflow/gnn#525]
I've installed all the things, gettext-runtime_0.18.1.1-2, glib_2.28.8-1, pkg-config_0.26-1, arrow-cpp, pyarrow(12.0.1) and r-arrow that I've suffered during installing tensorflow_gnn. But, eventually, I got another one, "No package 'arrow-python' found" error that I cannot solve even though pyarrow was installed and I spent a lot of time.

So, what should I know and solve to install tensorflow_gnn? Could you show me the right description or manual to install tensorflow_gnn successfully?

I tried to install it using pip install tensorflow_gnn.

**Comment by phanein** [comment]
Hi @PeterDeSOM,

Sorry to hear about your trouble here.  This strikes me as a likely Apache beam dependency issue.  The good news is that most of tf-gnn doesn't use beam.

Does this issue occur when using a virtual environment?  

The easiest path forward for you might probably be to exclude beam from setup.py (and handle the beam installation seperately if you really want to use distributed sampling).

We'll see if we can make a low dependency package available to alleviate this kind of headache in the future.

**Comment by mihirparadkar** [comment]
Hi @PeterDeSOM,

Could you let us know what system/platform this is on?

**Comment by PeterDeSOM** [comment]
OS: Windows 10
ENV:
- conda 22.9.0
- Python 3.11.4
- tensorflow 2.13.0

**Comment by PeterDeSOM** [comment]
The problem was the Python version. It can be installed on Python version under 11.

But, "No module named 'keras.engine'" error was occurred.
When I checked the keras is install, "Requirement already satisfied: keras in d:\tools\anaconda3\envs\tf\lib\site-packages (2.13.1)" message I got.

Plz, tell me how to fix it. I searched a lots of similar case, but I cannot find the solution to fix it.

**Comment by mihirparadkar** [comment]
Hi Peter,

Could you try uninstalling your current version and then reinstalling the newest release (0.6.0)?

**Comment by arnoegw** [comment]
There was no response in the last 2 months. Is this problem still current?
