### ISSUE TITLE
If plan to launch a pretrained model? is it possible to fine-tune or transfer-learning for tf-gnn?

### ISSUE THREAD

**Issue by SidneyLann** [tensorflow/gnn#575]

**Comment by Neslihans** [comment]
Hi There!

Can you please describe in more detail what you want to accomplish? Is there a specific model you've trained that you'd want to later fine-tune or are you looking for architectures to help you transfer learn from one domain to another?

**Comment by SidneyLann** [comment]
Hi. I want a gnn pretrained model with architecture and weights like pretrained bert in pln, pretrained yolov8 model in object detect, and then use custom data to fine-tune or train some layers in the pretrained gnn model.

**Comment by phanein** [comment]
Yes, TF-GNN works just like normal Keras layers in this way (so you should be able to achieve fine-tuning / transfer learning by basically following this tutorial: https://keras.io/guides/transfer_learning/).

**Comment by SidneyLann** [comment]
I mean is there a gnn pretrained model provided by offical to use?

**Comment by phanein** [comment]
Sorry about the delay - no, we don't provide pretrained GNN models.  (However you can use pretrained models provided by others with our framework, for example if you needed an encoder for images or text.)

**Comment by SidneyLann** [comment]
BERT, Yolov8, etc are powerfull for its weights, not only nn.
