### ISSUE TITLE
How to express the edge weight when aggregating neighbor nodes?

### ISSUE THREAD

**Issue by OysterQAQ** [tensorflow/gnn#615]
Is it implemented using the features parameter of EdgeSet?

**Comment by theDebugger811** [comment]
Hello @OysterQAQ , you can assign the `edge_weight_feature_name` in [GCNConv](https://github.com/tensorflow/gnn/blob/main/tensorflow_gnn/models/gcn/gcn_conv.py) and the edge weight will be incorporated when aggregating neighbour nodes as shown by this [snippet](https://github.com/tensorflow/gnn/blob/09dcf290044833d6c9403366273868e452991338/tensorflow_gnn/models/gcn/gcn_conv.py#L266).

Hope this answers your question.

**Comment by OysterQAQ** [comment]
@theDebugger811 Thank you for your reply. I want to implement PinSAGE, which improves upon GraphSAGE by enabling aggregation with edge-weighted features. Currently, my implementation looks like this. I use the edge weight as a feature of the edge set and then extend the `GraphSAGEPoolingConv` to create `PinSAGEPoolingConv`, in which I include a method to retrieve edge weights.

```python
def neighbour_weight(graph_tensor: GraphTensor,
                     edge_set_name: EdgeSetName,
                     node_tag: IncidentNodeTag,
                     *,
                     feature_value: Optional[Field] = None,
                     feature_name: Optional[FieldName] = None) -> Field:
    return tf.expand_dims(graph_tensor.edge_sets[edge_set_name].features["w"], axis=1)
```

I override the `call` method and include the following:

```python
 neighbour_weight_from_edge = (
                lambda feature_value: neighbour_weight(
                    graph, edge_set_name, sender_node_tag,
                    feature_value=feature_value))
```

Then, in the `convolve` method, which is actually called:

```python
result = self._pooling_transform_fn(result)
weight = neighbour_weight_from_edge(sender_node_input)
# Applying edge weights
result = result * weight
result = pool_to_receiver(result, reduce_type=self._reduce_type)
```

**Comment by arnoegw** [comment]
Sounds like you found a way forward! Is there any problem left to track in this issue, or may we close it?
