### ISSUE TITLE
How does tensorflow-gnn handle the mapping between node feature vector and node index?

### ISSUE THREAD

**Issue by whitezulu** [tensorflow/gnn#71]
How does tensorflow-gnn handle the mapping between node feature vector and node index? If the feature vector of a node is input, can tensorflow-gnn automatically know which node it is?

**Comment by arnoegw** [comment]
The feature vectors for all nodes in a node set are stored together in a single Tensor. The feature vector for node $i$ is found in that tensor at index $i$. For more details, please see the [TF-GNN paper](https://arxiv.org/abs/2207.03522v1), esp. Figures 2b and 3, as well as the [GraphTensor guide](https://github.com/tensorflow/gnn/blob/main/tensorflow_gnn/docs/guide/graph_tensor.md).
