### ISSUE TITLE
graph with multiple same direction edges (but different feature) between two nodes

### ISSUE THREAD

**Issue by cherryCookies** [tensorflow/gnn#782]
To whom it may concern.

I have a question regarding the usage of multiple edges which all are from same source node and heading to another same target node. (visual explanation below)
![스크린샷 2023-12-26 오후 4 53 24](https://github.com/tensorflow/gnn/assets/114276629/6f6f87d1-18eb-4487-9174-1b5c573eccab)

In case where they have different edge features(2 x 1) to others, is this concept of "duplicated edges" recognised during GNN training? Or the duplicity is ignored and they deal with training as a single consensus edge?
 
Kind regards
Charyeong Heo

**Comment by blais** [comment]
It' s been a while since I've been involved in the project but I think the data model lets you create training data with distinct edge sets to the same (source, destination) sets of nodes, and to create a custom model treating them separately if you want.

**Comment by aferludin** [comment]
Let me confirm Martin's answer. Library supports parallel edges (multiple edges that connect the same pair of nodes) and there could be multiple edge sets (with unique names) that connect the same pair of node sets. There is no special treatment for the parallel edges, e.g. 


```
import tensorflow as tf
import tensorflow_gnn as tfgnn

# edges: 0->0, 0->0, 0->1, 0->1
gt = tfgnn.homogeneous(
    tf.constant([0, 0, 0, 0]),
    tf.constant([0, 0, 1, 1]),
    edge_features={'feat': tf.constant([1, 2, 3, 4])},
    node_set_sizes=tf.constant([2]),
)
# result: 3=1+2, 7=3+4
tfgnn.pool_edges_to_node(gt, 'edges', tfgnn.TARGET, feature_name='feat')
```

**Comment by cherryCookies** [comment]
Many thanks to @blais and @aferludin. How thoughtful you guys are!
With a help from example code, I understood how pooling originally treats the parallel edges distinct from one another.
I might want to make certain the parallel edges are processed separately by customising the model.
Thank you for answering my silly question :)
