### ISSUE TITLE
Using tfgnn with tflite without graphtensor input

### ISSUE THREAD

**Issue by kohlisimranjit** [tensorflow/gnn#799]
Hi,
I am trying to have a minimum footprint deployment of a tensorflow gnn model. Seems that the tf-GNN models take in graphTensor as input which would require both tensorflow and tfgnn libraries to be present. Is there a way to have tf-GNN lite model to run inference without needing to import the tfgnn library? Thanks!

**Comment by arnoegw** [comment]
Yes, please see issue https://github.com/tensorflow/gnn/issues/33#issuecomment-2049220142 and the links given there.
