### ISSUE TITLE
Broken link in documentation.

### ISSUE THREAD

**Issue by tbaker2** [tensorflow/gnn#8]
The link to the collab workbook in the overview under Building Models points to a private document.
Document: https://github.com/tensorflow/gnn/blob/main/tensorflow_gnn/docs/guide/overview.md
Link: https://colab.sandbox.google.com/drive/1sDIHr_-XvhKGXcFEQf1F4NiRDa9x8gTH

**Comment by arnoegw** [comment]
Thanks, @tbaker2! Proper links were put in place by commit https://github.com/tensorflow/gnn/commit/0031551ffd26d73ee83df214bde87b92de47fab0
