### ISSUE TITLE
How to construct samples that contain both graphs and other features? For example, (graph, feature_1, feature_2, ...).

### ISSUE THREAD

**Issue by OysterQAQ** [tensorflow/gnn#806]

**Comment by arnoegw** [comment]
The input to a Keras Model can be any nest of tensors, including the kind of tuple you sketched.

For deserialization from `tf.train.Example`, esp. in the presence of more than one GraphTensor, the `prefix=` argument of [`tfgnn.parse_example()`](https://github.com/tensorflow/gnn/blob/main/tensorflow_gnn/docs/api_docs/python/tfgnn/parse_example.md) might come in handy.

Alternatively, if each example has one graph plus some freestanding features, consider packing the freestanding features into the `Graph.context`, see the [Data Preparation and Sampling](https://github.com/tensorflow/gnn/blob/main/tensorflow_gnn/docs/guide/data_prep.md) guide.
