### ISSUE TITLE
Is it possible to port a trained gnn model to TensorFlow Lite (TFLite) for use in Java/Android applications?

### ISSUE THREAD

**Issue by knn1989** [tensorflow/gnn#808]
Hello,

Is it possible to port a trained gnn model to TensorFlow Lite (TFLite) for use in Java/Android applications?

If so, how are the input and output buffers declared? For instance, with a regular TFLite model, we typically use FloatBuffer or IntBuffer in Java/Android.

Could you provide an example?

Thank you.

**Comment by arnoegw** [comment]
Yes, this is possible; please see issue https://github.com/tensorflow/gnn/issues/33#issuecomment-2049220142 and the links given there.
