### ISSUE TITLE
outdated jupyter notebook

### ISSUE THREAD

**Issue by ghts2110** [tensorflow/gnn#837]
The datasets class is no longer in the tensorflow_gnn.experimental.in_memory path and is giving this error:

ModuleNotFoundError: No module named 'tensorflow_gnn.experimental.in_memory'

f5c88f4ee2133a25e3f4f53183ccbea8f1226d17

**Comment by arnoegw** [comment]
The colab notebooks for particular events (such as the NeurIPS 2022 Tutorial) capture exactly what was presented there. Some experimental parts of the library have been changed or removed for the 1.0 release. To re-run the old colab notebook, please try and pip install the version of tensorflow-gnn that was current at the time.
