### ISSUE TITLE
Apple M1 installation issue

### ISSUE THREAD

**Issue by beppe2hd** [tensorflow/gnn#92]
I'm trying to install tensoflow_gnn on my apple m1 but I got the error message:

`beppe2hd@192 gnnInvestigation % pip install tensorflow_gnn
Collecting tensorflow_gnn
  Using cached tensorflow_gnn-0.2.1-py3-none-any.whl (364 kB)
Collecting pyarrow
  Using cached pyarrow-9.0.0-cp39-cp39-macosx_11_0_arm64.whl (21.6 MB)
Collecting apache-beam
  Using cached apache-beam-2.40.0.zip (2.8 MB)
  Preparing metadata (setup.py) ... done
Collecting networkx
  Using cached networkx-2.8.5-py3-none-any.whl (2.0 MB)
Collecting tensorflow_gnn
  Using cached tensorflow_gnn-0.2.0-py3-none-any.whl (364 kB)
  Using cached tensorflow_gnn-0.1.0-py3-none-any.whl (196 kB)
Collecting scipy
  Using cached scipy-1.9.0-cp39-cp39-macosx_12_0_arm64.whl (29.9 MB)
Collecting matplotlib
  Downloading matplotlib-3.5.3-cp39-cp39-macosx_11_0_arm64.whl (7.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.2/7.2 MB 6.5 MB/s eta 0:00:00
Requirement already satisfied: numpy in /Users/beppe2hd/miniforge3/envs/gnnInvestigation/lib/python3.9/site-packages (from tensorflow_gnn) (1.22.4)
Requirement already satisfied: protobuf>=3.17 in /Users/beppe2hd/miniforge3/envs/gnnInvestigation/lib/python3.9/site-packages (from tensorflow_gnn) (3.19.4)
Collecting pygraphviz
  Downloading pygraphviz-1.9.zip (119 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.9/119.9 kB 2.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /Users/beppe2hd/miniforge3/envs/gnnInvestigation/lib/python3.9/site-packages (from tensorflow_gnn) (1.15.0)
Requirement already satisfied: grpcio in /Users/beppe2hd/miniforge3/envs/gnnInvestigation/lib/python3.9/site-packages (from tensorflow_gnn) (1.48.0)
ERROR: Cannot install tensorflow-gnn==0.1.0, tensorflow-gnn==0.2.0 and tensorflow-gnn==0.2.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    tensorflow-gnn 0.2.1 depends on tensorflow>=2.7.0
    tensorflow-gnn 0.2.0 depends on tensorflow>=2.7.0
    tensorflow-gnn 0.1.0 depends on tensorflow-cpu>=2.7.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts`

I'm currently used the tensoflow installation proposed at https://developer.apple.com/metal/tensorflow-plugin/ that install the version 2.9.2
`import tensorflow as tf
tf.__version__
'2.9.2'`

but it seems that tensor flow gun does not correctly detect the tensor flow version.

Also the manual installation produce similar error

**Comment by arnoegw** [comment]
Are you trying to install multiple versions of tensorflow-gnn at once? Please install just one; we recommend the latest stable (at this time, 0.2.1).

**Comment by voloshink** [comment]
I passed in  --no-deps for pip install (python3 -m pip install tensorflow_gnn==0.3.0 --no-deps) to ignore the pip complaint and that seemed to work

**Comment by arnoegw** [comment]
Sorry for the slow response. I believe this has been fixed soon after with comment https://github.com/tensorflow/gnn/commit/e6ce2ac37b6f2ce27e12fb61405d5797b7a7b500
