### ISSUE TITLE
examples/in_memory programs import functions incorrectly.

### ISSUE THREAD

**Issue by tbaker2** [tensorflow/gnn#97]
In the examples/in_memory/tf_trainer.py file are the following lines (30-32).
```
from tensorflow_gnn.examples.in_memory import datasets
from tensorflow_gnn.examples.in_memory import models
from tensorflow_gnn.examples.in_memory import reader_utils
```
The tfgnn installed package doesn't have an examples directory so these lines fail. Removing the strings `from tensorflow_gnn.examples.in_memory `, and importing locally will run.

**Comment by arnoegw** [comment]
Hi @tbaker2 , thanks for reporting the issue! @mihirparadkar has fixed the import statements in commit 
https://github.com/tensorflow/gnn/commit/ea4231a433a7e32bdd2effca07b46221dbc037f6 (with some change to how they are exported out of Google's repo).
